MODEL:
  NUM_CLASSES: 3
  BACKBONE:
    NAME: "efficient_net-b3"
    OUT_CHANNELS: (48, 136, 384, 256, 256, 256)
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_train", )
  TEST: ("voc_test", )
SOLVER:
  MAX_ITER: 10000
  LR_STEPS: [6000, 8000]
  GAMMA: 0.1
  BATCH_SIZE: 24
  LR: 1e-3

OUTPUT_DIR: "/content/SSD/outputs/efficient_net_b3_ssd300_voc0712"
