MODEL:
  NUM_CLASSES: 3                   # VOC classes + background
  META_ARCHITECTURE: "SSDDetector"
  BACKBONE:
    NAME: "efficientnet_b3"
    OUT_CHANNELS: (384, 512, 768, 1536, 512, 256)  # Adjust based on actual channels
  BOX_HEAD:
    NAME: "SSDBoxHead"
    PREDICTOR: "SSDBoxPredictor"
  PRIORS:
    FEATURE_MAPS: [38, 19, 10, 5, 3, 1]  # Spatial sizes
    STRIDES: [8, 16, 32, 64, 128, 256]   # Relative to input
    MIN_SIZES: [15, 30, 60, 111, 162, 213]
    MAX_SIZES: [30, 60, 111, 162, 213, 264]
    ASPECT_RATIOS: [[2], [2,3], [2,3], [2,3], [2], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_train", )
  TEST: ("voc_test", )
SOLVER:
  MAX_ITER: 10000
  LR_STEPS: [6000, 8000]
  LR: 1e-3
  GAMMA: 0.1
  BATCH_SIZE: 24
OUTPUT_DIR: "/content/output"