MODEL:
  NUM_CLASSES: 3
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_train", )
  TEST: ("voc_test", )
SOLVER:
  MAX_ITER: 10000
  LR_STEPS: [6000, 8000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: "outputs/vgg_ssd300_voc0712"
